version: 2
updates:
  - package-ecosystem: nuget
    directory: "/src/simple-api/src/api"
    schedule:
      interval: weekly
      day: monday
      timezone: Europe/London
    open-pull-requests-limit: 10
    rebase-strategy: disabled

  - package-ecosystem: nuget
    directory: "/src/simple-api/src/tests/Functional"
    schedule:
      interval: weekly
      day: monday
      timezone: Europe/London
    open-pull-requests-limit: 10
    rebase-strategy: disabled

  - package-ecosystem: nuget
    directory: "/src/cqrs/src/api"
    schedule:
      interval: weekly
      day: monday
      timezone: Europe/London
    open-pull-requests-limit: 10
    rebase-strategy: disabled

  - package-ecosystem: nuget
    directory: "/src/cqrs/src/tests/Functional"
    schedule:
      interval: weekly
      day: monday
      timezone: Europe/London
    open-pull-requests-limit: 10
    rebase-strategy: disabled

  - package-ecosystem: terraform
    directory: "/deploy/azure/app/kube"
    schedule:
      interval: weekly
      day: monday
      timezone: Europe/London
    open-pull-requests-limit: 10
    rebase-strategy: disabled
  
  - package-ecosystem: terraform
    directory: "/deploy/aws/app/kube"
    schedule:
      interval: weekly
      day: monday
      timezone: Europe/London
    open-pull-requests-limit: 10
    rebase-strategy: disabled
