# Configuration file for setting up the project

framework:
  name: dotnet
  commands:
    - name: dotnet
      version: ">= 6.0, < 6.1"

# Pipeline files
pipeline:
  # Pipeline files for ADO
  - type: azdo
    files:
      - name: build
        path: build/azDevOps/azure/air-api.yml
      - name: variable
        path: build/azDevOps/azure/air-api-vars.yml
    templates:
      - name: variable
        path: build/azDevOps/azure/air-api-vars_TEMPLATE.yml
    replacements:
      - pattern: ^.*ensono-sp-creds$
        value: ""
  # Pipeline files for GHA
  - type: gha
    files:
      - name: variable
        path: .github/workflows/ci.env
    templates:
      - name: variable
        path: .github/workflows/ci.env

# The init stage are things that are required to run before the template is run
init:
  operations:
    - action: cmd
      cmd: dotnet
      args: new -i .
      desc: Install stacks templates from the repo directory
    - action: cmd
      cmd: dotnet
      args: new stacks-{{ .Project.Framework.Option }} -n {{ .Input.Business.Company }}.{{ .Input.Business.Domain }} --domain {{ .Input.Business.Domain }} --cloudProvider {{ .Input.Cloud.Platform }} --cicdProvider {{ .Input.Pipeline }} -o {{ .Project.Directory.WorkingDir }}
      desc: Create a project using the stacks template
    - action: cmd
      cmd: dotnet
      args: new --uninstall {{ .Project.Directory.TempDir }}
      desc: Remove the temporary template from dotnet
