import:
  - ./build/taskctl/contexts.yaml
  - ./build/taskctl/tasks.yaml

watchers:

  lint:
    watch:
      - "*.yml"
    events: [create, write]
    task: lint:yaml

pipelines:

  setup:
    - task: buildnumber

  lint:
    - task: lint:yaml
    - task: lint:terraform:format
    - task: lint:terraform:validate

  # Pipeline to perform the build of the project
  build:
    - pipeline: lint

    - task: test:unittest
    - task: test:component
    - task: test:integration
    - task: test:contract
    - task: test:coverage
      depends_on:
        - test:unittest
    # TODO: Temporarily disabled due to AIR compatibility issues. Logged via Bug 4315
    # - task: test:sonarcloud:start
    # - task: test:sonarcloud:stop
    #   depends_on:
    #     - test:unittest
    #     - test:component
    #     - test:integration
    #     - test:contract
    - task: build:functional_tests
    - task: build:container
      depends_on:
        - test:unittest
        - test:component
        - test:integration
        - test:contract
      variables:
        IMAGE_NAME: stacks-api

  # Pipeline to ensure that the infrastructure is valid
  infrastructure:
    - task: infra:init
    - task: infra:plan
      depends_on: infra:init
    - task: infra:apply
      depends_on: infra:plan
      # - task: infra:output
      #   depends_on: infra:apply

  # Deploy pipeline
  deploy:
    # - task: infra:output
    - task: deploy:templater
    #  depends_on: infra:output
    # - task: deploy:kubernetes
    #   depends_on: deploy:templater
