# Import contexts and tasks for Taskctl
import:
  - ./build/taskctl/contexts.yaml
  - ./build/taskctl/tasks.yaml

watchers:
  lint:
    watch:
      - '*.yml'
    events: [create, write]
    task: lint:yaml

pipelines:
  setup:
    - task: debug:env
    - task: buildnumber
      depends_on:
        - debug:env

  lint:
    - task: lint:yaml
    - task: lint:terraform:format
    - task: lint:terraform:validate

  # Pipeline to perform the build of the project
  build:
    - pipeline: lint
    - task: test
    - task: build:functional_tests
      depends_on:
        - test
    - task: build:container
      depends_on:
        - test
      variables:
        IMAGE_NAME: stacks-api

  # Pipeline to ensure that the infrastructure is valid
  infrastructure:
    - task: infra:init
    - task: infra:plan
      depends_on: infra:init
    - task: infra:apply
      depends_on: infra:plan

  # TODO: This should be removed when we can supply all the TF args as a single env var
  infrastructure:aws:
    - task: infra:init:aws
    - task: infra:plan
      depends_on: infra:init:aws
    - task: infra:apply
      depends_on: infra:plan


  # Deploy pipeline
  deploy:
    - task: infra:init
    - task: deploy:templater
      depends_on: infra:init
    - task: deploy:kubernetes
      depends_on: deploy:templater
    - task: deploy:functional_tests
      depends_on: deploy:kubernetes

  # Deploy pipeline # TODO: This should be removed when we can supply all the TF args as a single env var
  deploy:aws:
    - task: infra:init:aws
    - task: deploy:templater
      depends_on: infra:init:aws
    - task: deploy:kubernetes
      depends_on: deploy:templater
    - task: debug:sleep
      depends_on: deploy:kubernetes
      variables:
        - sleep: 30
    - task: deploy:functional_tests
      depends_on: debug:sleep
