contexts:
  powershell:
    executable:
      bin: docker
      args:
        - run
        - --rm
        - -v
        - ${PWD}:/app
        - -e
        - PSModulePath=/app/modules
        - -w
        - /app
        - russellseymour/runner-pwsh-dotnet
        - pwsh
        - -NoProfile
        - -Command
    quote: "'"
    env:
      arguments: "-v q /p:CollectCoverage=true /p:CoverletOutputFormat=opencover"

tasks:

  buildnumber:
    context: powershell
    description: Update the build number
    command:
      - Update-BuildNumber

  lint:
    context: powershell
    description: Perform linting checks
    command:
      - Invoke-YamlLint
      - Invoke-TerraformLint -Format
      - Invoke-TerraformLint -Validate

  # TESTS
  # Configure test tasks
  test:sonarcloud:start:
    context: powershell
    description: Run SonarCloud tests
    command:
      - Invoke-SonarScanner -start -buildversion $BUILD_BUILDNUMBER
      - Build-Dotnet
    condition: exit $SONAR_NO_RUN

  # Stop the static code analyise
  # TODO - need to work out why the coverage files are being modified in the original build
  test:sonarcloud:stop:
    context: powershell
    description: Run SonarCloud tests
    command:
      - Invoke-SonarScanner -stop
    condition: exit $SONAR_NO_RUN

  test:unittest:
    context: powershell
    description: Perform unit tests
    command:
      - Invoke-DotNetTests
    env:
      pattern: "*UnitTests"
    condition: exit $UNITTEST_NO_RUN

  test:component:
    context: powershell
    description: Perform component tests
    command:
      - Invoke-DotNetTests
    env:
      pattern: "*ComponentTests"
    condition: exit $COMPONENTTEST_NO_RUN

  # TODO: Need to work out how to pass in additional environment variables that may have been set
  # They will not always have the same name so we need to accept a list of them, which may not always
  # be formatted correctly for this conversion to be done
  test:integration:
    context: powershell
    description: Perform Integration tests
    command:
      - Invoke-DotNetTests
    env:
      pattern: "*IntegrationTests"
    condition: exit $INTEGRATIONTEST_NO_RUN

  # TODO: Need to work out how to pass in additional environment variables that may have been set
  # They will not always have the same name so we need to accept a list of them, which may not always
  # be formatted correctly for this conversion to be done
  test:contract:
    context: powershell
    description: Perform contract tests
    command:
      - Invoke-DotNetTests
    env:
      pattern: "*ContractTests"
    condition: exit $CONTRACTTEST_NO_RUN

  test:coverage:
    context: powershell
    description: Generate test coverage reports
    command:
      - Invoke-DotNetCoverage -target $PROJECT_ROOT_DIR/coverage

  build:container:
    context: powershell
    description: Create container image for application
    command:
      - Build-DockerImage -buildargs src/api -push

  build:functional_tests:
    context: powershell
    description: Build functional tests for integration testing
    command:
      - Build-Dotnet -workingDirectory src/tests/Functional

pipelines:

  # Pipeline to perform the build of the project
  build:
    - task: lint
    - task: buildnumber
    - task: test:sonarcloud:start
    - task: test:unittest
    - task: test:component
    - task: test:integration
    - task: test:contract
    - task: test:coverage
      depends_on:
        - test:unittest
    - task: test:sonarcloud:stop
      depends_on:
        - test:unittest
        - test:component
        - test:integration
        - test:contract
    - task: build:functional_tests
    - task: build:container
      depends_on: test:sonarcloud:stop
