extends: default

yaml-files:
  - '*.yml'
  - '*.yaml'

ignore: |
  .terraform/
  bin/
  obj/
  **/contracts/openapi-v1.yaml
  deploy/helm/stacks-dotnet/
  /app/deploy/helm/stacks-dotnet/

rules:
  document-start: disable
  line-length: disable
  truthy: disable
  comments-indentation: disable
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false
