apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- if eq .Values.ingress.cloudProvider "azure" -}}
    {{- with .Values.ingress.annotations.azure }}
  annotations:
    {{- toYaml . | nindent 8 }}
    {{- end }}
  {{- end -}}
  {{- if eq .Values.ingress.cloudProvider "aws" -}}
    {{- with .Values.ingress.annotations.aws }}
  annotations:
    {{- toYaml . | nindent 8 }}
    {{- end }}
  {{- end -}}
    {{- include "stacks-dotnet.annotations" . | nindent 8 }}
  labels:
    {{- include "stacks-dotnet.labels" . | nindent 8 }}
  name: {{ include "stacks-dotnet.fullname" . }}
  namespace: {{ .Values.namespace }}
{{- if eq .Values.ingress.cloudProvider "aws" }}
  finalizers:
  - ingress.k8s.aws/resources
  {{- end}}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          {{- if eq .Values.ingress.cloudProvider "azure" }}
          - path: {{ .Values.ingress.path }}(/|$)(.*)
          {{- end}}
          {{- if eq .Values.ingress.cloudProvider "aws" }}
          - path: "{{ .Values.ingress.path }}/*"
          {{- end}}
            pathType:  {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "stacks-dotnet.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
