apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- include "stacks-dotnet.annotations" . | nindent 8 }}
    {{- if eq .Values.ingress.cloudProvider "aws" }}
        alb.ingress.kubernetes.io/healthcheck-path: ${k8s_app_route}/swagger/index.html
    {{- end }}
  name: {{ include "stacks-dotnet.fullname" . }}
  labels:
    {{- include "stacks-dotnet.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  {{- if eq .Values.ingress.cloudProvider "aws" }}
  type: NodePort
  {{ else }}
  type: {{ .Values.service.type }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "stacks-dotnet.selectorLabels" . | nindent 4 }}
