apiVersion: v1
kind: Service
metadata:
  name: {{ include "stacks-dotnet.fullname" . }}
  labels:
    {{- include "stacks-dotnet.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http

