name: 'Install taskctl'
description: 'Downloads and installs taskctl'
runs:
  using: 'composite'
  steps:
    - run: |
        env
        wget https://github.com/taskctl/taskctl/releases/download/$TaskctlVersion/taskctl_$TaskctlVersion_linux_amd64.tar.gz -O /tmp/taskctl.tar.gz
        tar zxf /tmp/taskctl.tar.gz -C /usr/local/bin taskctl
      shell: bash
      # env:
      #   TaskctlVersion: ${{ env.TaskctlVersion }}
