name: 'Install taskctl'
description: 'Downloads and installs taskctl'
runs:
  using: 'composite'
  steps:
    - run: |
        wget https://github.com/taskctl/taskctl/releases/download/${{ env.TaskctlVersion }}/taskctl_${{ env.TaskctlVersion }}_linux_amd64.tar.gz -O /tmp/taskctl.tar.gz
        tar zxf /tmp/taskctl.tar.gz -C /usr/local/bin taskctl
      shell: bash
