apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    {{- include "stacks-dotnet.annotations" . | nindent 8 }}
  labels:
    {{- include "stacks-dotnet.labels" . | nindent 4 }}
  name: {{ include "stacks-dotnet.fullname" . }}
  namespace: {{ .Values.namespace }}
data:
  appsettings.json: |
    {
      "Serilog": {
          "Using": [
              "Serilog.Sinks.Console",
              "Serilog.Sinks.ApplicationInsights"
          ],
          "MinimumLevel": {
              "Default": " {{ .Values.pod.loglevel }}",
              "Override": {}
          },
          "WriteTo": [
              { "Name": "Console" },
              {
                  "Name": "ApplicationInsights",
                  "Args": {
                      "telemetryConverter": "Serilog.Sinks.ApplicationInsights.Sinks.ApplicationInsights.TelemetryConverters.TraceTelemetryConverter, Serilog.Sinks.ApplicationInsights"
                  }
              }
          ],
          "Enrich": [ "FromLogContext", "WithMachineName", "WithThreadId" ],
          "Destructure": [],
          "Properties": {
              "Application": "Menu API"
          }
      },
      "AllowedHosts": "*",
      "CosmosDb": {
          "DatabaseAccountUri": "{{ .Values.app.cosmosdbendpoint }}",
          "DatabaseName": "{{ .Values.app.cosmosdbname }}",
          "SecurityKeySecret": {
              "Identifier": "COSMOSDB_KEY",
              "Source": "Environment"
          }
      },
      "JwtBearerAuthentication": {
          "Audience": "${jwtbearerauthentication_audience}",
          "Authority": "${jwtbearerauthentication_authority}",
          "Enabled": false,
          "OpenApi": {
              "AuthorizationUrl": "${jwtbearerauthentication_openapiauthorizationurl}",
              "ClientId": "${jwtbearerauthentication_openapiclientid}",
              "TokenUrl": "${jwtbearerauthentication_openapitokenurl}"
          }
      },
      "TestConfig": "Test value from file",
      "Values": {
        "Items": [
          "Item A from config",
          "Item B from congig",
          "Item C from config"
        ]
      },
      "ServiceBusConfiguration": {
        "Sender": {
          "Topics": [
            {
              "Name": "{{ .Values.app.sbtopic }}",
              "ConnectionStringSecret": {
                  "Identifier": "SERVICEBUS_CONNECTIONSTRING",
                  "Source": "Environment"
              }
            }
          ]
        }
      }
    }