apiVersion: v1
kind: Secret
metadata:
  annotations:
    {{- include "stacks-dotnet.annotations" . | nindent 8 }}
  labels:
    {{- include "stacks-dotnet.labels" . | nindent 8 }}
  name: {{ include "stacks-dotnet.secretName" . }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  app_insights: {{ .Values.pod.appInsightsKey | b64enc | quote }}
  cosmos_key: {{ .Values.app.cosmosdbkey | b64enc | quote  }}
  servicebus_connectionstring: {{ .Values.app.sbconnectionstring | b64enc | quote }}