apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    {{- include "stacks-dotnet-worker.annotations" . | nindent 8 }}
  labels:
        aadpodidbinding: {{ .Values.aadPodIdentityBinding }}
    {{- include "stacks-dotnet-worker.labels" . | nindent 8 }}
  name: {{ include "stacks-dotnet-worker.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  progressDeadlineSeconds: 600
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      {{- include "stacks-dotnet-worker.selectorLabels" . | nindent 8 }}

  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        {{- include "stacks-dotnet-worker.annotations" . | nindent 8 }}

      labels:
        aadpodidbinding: {{ .Values.aadPodIdentityBinding }}
      {{- include "stacks-dotnet-worker.selectorLabels" . | nindent 8 }}
    spec:
      dnsPolicy: ClusterFirst
      # New Config
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "stacks-dotnet.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: worker
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.name }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ENVIRONMENT
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['environment']
            - name: VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['version']
            - name: RELEASE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['release']
            - name: API_BASEPATH
              value: {{ .Values.ingress.path }}
            - name: COSMOSDB_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "stacks-dotnet.secretName" . }}
                  key: cosmos_key
            - name: LOG_LEVEL
              value: {{ .Values.pod.loglevel }}
            - name: APPINSIGHTS_INSTRUMENTATIONKEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "stacks-dotnet.secretName" . }}
                  key: app_insights
            - name: SERVICEBUS_CONNECTIONSTRING
              valueFrom:
                secretKeyRef:
                  name: {{ include "stacks-dotnet.secretName" . }}
                  key: servicebus_connectionstring
          volumeMounts:
            - name: workerappsettings
              mountPath: /app/config
      volumes:
        - name: workerappsettings
          configMap:
            name: {{ include "stacks-dotnet-worker.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
